### ISSUE TITLE
phyloseq_replace_zero and phyloseq_transform_aldex_clr

### ISSUE THREAD

**Issue by javiercnav** [vmikk/metagMisc#10]
Hello, I can see documentation for the functions phyloseq_replace_zero and phyloseq_transform_aldex_clr, however these are not available in the R package. Is it that they don't work?
Thanks a lot!
https://rdrr.io/github/vmikk/metagMisc/src/R/phyloseq_transform.R#sym-phyloseq_transform_aldex_clr

**Comment by vmikk** [comment]
Hello!
My apologies for the slow reply.
These functions should be working, I just forgot to include them in the `NAMESPACE` file so they could be exported.
I plan to update the package in the nearest future and I'll fix this issue as well.
