### ISSUE TITLE
Average rarified OTU/ASV table after multiple rarefaction

### ISSUE THREAD

**Issue by shreyaskumbhare** [vmikk/metagMisc#20]
Hi @vmikk. I am finding this package very useful. I am currently trying to perform multiple rarefaction using phyloseq_mult_raref function. What I need to achieve is an average rarified table of all the iterations. I have used the other function i.e. phyloseq_mult_raref_avg, however the output is a relative abundance matrix. I would really appreciate it if you could help me out in obtaining an averaged rarified table with absolute abundance, instead of relative abundance.

Thanks!

**Comment by vmikk** [comment]
Hello Shreyas!

To get the table with absolute abundances averaged across rarefactions, you may just multiply relative abundances by rarefaction depth. It should be equivalent to the averaging of absolute abundances, isn't it?

E.g.,
```
raref_depth <- 100

data(esophagus)
rr <- phyloseq_mult_raref_avg(esophagus, SampSize = raref_depth, iter = 10)
rr <- transform_sample_counts(rr, function(x){ x * raref_depth })

head(otu_table(rr))
```
Please note, that average abundances could be fractional.

With kind regards,
Vladimir

**Comment by shreyaskumbhare** [comment]
Yeah, this makes sense!! Thanks @vmikk! I had another query, can you elaborate on what exactly does the "replace" parameter do and is it recommended to use?
