### ISSUE TITLE
[adonis_pairwise function] Deprecation notice: Replace vegan::adonis with vegan::adonis2

### ISSUE THREAD

**Issue by Ebedthan** [vmikk/metagMisc#25]
Dear @vmikk,

I suggest to substitute vegan::adonis with vegan::adonis2 because:
- According to the vegan manual, "adonis2 replaces adonis with extended functionality and completely new internal design"
- vegan::adonis is now deprecated and could be retired entirely in the next vegan version.

I can prepare a PR if needed.

Thanks.

**Comment by vmikk** [comment]
Hello Anicet!

Thank you for your suggestion! I appreciate your input and your offer to help.
I've taken your advice and updated the package to substitute `vegan::adonis` with `vegan::adonis2`.

Thank again!

**Comment by vmikk** [comment]
The issue has been addressed and closed via commit 9c56246.
