### ISSUE TITLE
Prevalence function missing from install

### ISSUE THREAD

**Issue by LukDrey** [vmikk/metagMisc#26]
Hi vmikk, 

loving the package! 

I just wanted to make you aware that using devtools::install_github("vmikk/metagMisc") somehow does not install the _prevalence()_ function. I am not sure if I am doing something wrong or if it is a problem. 

Best 

Lukas

**Comment by vmikk** [comment]
Hello Lucas @LukDrey !

Thank you for reporting this issue!
It appears that I overlooked exporting this function to the package's namespace.
In the meantime, you can use this function by invoking it through `metagMisc:::prevalence(physeq)`.

With kind regards,
Vladimir

**Comment by LukDrey** [comment]
Hi Vladimir, 

thanks for the quick response! I didn't know about the ::: method. Thanks for that! I defined the function myself from your source code, but obviously the ::: are more elegant. 

Best 

Lukas

**Comment by vmikk** [comment]
Closed via 4d875dd5102e7adeba50a316f2073b382b42648b
