### ISSUE TITLE
how to install 0.0.4 version 

### ISSUE THREAD

**Issue by JH966** [vmikk/metagMisc#30]
i got a problem using prevalence
how to install 0.0.4 version? 
i try 

devtools::install_version("metagMisc", verstion = 0.0.4)
Error: unexpected numeric constant in "devtools::install_version("metagMisc", verstion = 0.0.4"

and

devtools::install_version("metagMisc", 0.0.4)
Error: unexpected numeric constant in "devtools::install_version("metagMisc", 0.0.4"

remotes::install_version("metagMisc", version = 0.0.4)
Error: unexpected numeric constant in "remotes::install_version("metagMisc", version = 0.0.4"

remotes::install_github("metagMisc", 0.0.4)
Error: unexpected numeric constant in "remotes::install_github("metagMisc", 0.0.4"

devtools::install_github("metagMisc",0.0.4)
Error: unexpected numeric constant in "devtools::install_github("metagMisc",0.0.4"

please any suggestion

**Comment by vmikk** [comment]
To install the older version, you may use

```{R}
devtools::install_github("vmikk/metagMisc@v.0.0.4")   # v.0.0.4
```
or
```{R}
remotes::install_github("vmikk/metagMisc@v.0.0.4")
```
